#!/bin/bash
curl -fsSL https://get.docker.com/ | sh
sudo systemctl start docker  
sudo systemctl enable docker
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
